### ISSUE TITLE
Physics

### ISSUE THREAD

**Issue by AlexDeacy** [HandFeet/test#3]
**How do we want to handle physics**,
circular hit detection is very easy, and resolution is not too bad but made easier if we just use repulsive forces.
But I think Box2D is built into the engine. Not used it before, but might mean we can have more complex geometry in the asteroids and ship etc.

Alternately to start with we may just want to have no colliders and just do damage on impact.
eg: bullet collides and does damage but is destroyed, or asteroid hits ship destroying the asteroid and doing damage or ending the game.

**Comment by AlexDeacy** [comment]
Would be nice to have heavy physics based system,
eg: asteroid do damage dependant on relative speed,
or bullets are physical objects that after impact sluggishly drift off.

**Comment by AlexDeacy** [comment]
[Box2D Tutorial Link](http://www.gamefromscratch.com/post/2014/08/27/LibGDX-Tutorial-13-Physics-with-Box2D-Part-1-A-Basic-Physics-Simulations.aspx)

**Comment by HandFeet** [comment]
Box2D is now being used
